version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
        POSTGRES_DB: "Auction"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "123"
    volumes:
        - postgres-data:/var/lib/postgresql/data
    ports:
        - "77777:5432"

volumes:
    postgres-data: